

name: 'thesis'
version: '1.0'


profile: 'thesis'


source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

quoting:
  identifier: false
  schema: false

models:
  thesis:
    vars:
      ride_tables_1:
      - rides_201601
      - rides_201602
      - rides_201603
      - rides_201604
      - rides_201605
      - rides_201606
      - rides_201607
      - rides_201608
      - rides_201609

      ride_tables_2:
      - rides_2016010
      - rides_201611
      - rides_201612
      - rides_201701
      - rides_201702
      - rides_201703
      - rides_201704
      - rides_201705
      - rides_201706
      - rides_201707
      - rides_201708
      - rides_201709
      - rides_201710
      - rides_201711
      - rides_201712
