

name: 'thesis'
version: '1.0'


profile: 'thesis'


source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"

models:
  thesis: 
    
      example:
          materialized: view
