version: 2

models:
    - name: rides_weather_joined
      description: JOINS EVERYTHING
      columns:
          - name: start_time
            tests:
                - not_null
                - unique

    - name: fct_hourly_weather
      description: Converts to timestamp
      columns:
          - name: start_time
            tests:
                - not_null
                - unique

    - name: fct_hourly_rides
      description: Converts to timestamp and extracts additional date features
      columns:
          - name: start_time
            tests:
                - not_null
                - unique
